# coding: utf-8

"""
    Fax.to REST API client for Python

    This is Fax.to REST API client for Python.  # noqa: E501

    OpenAPI spec version: 2.0.0
    Contact: inquiries@fax.to
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.fax_sending_api import FaxSendingApi  # noqa: E501
from swagger_client.rest import ApiException


class TestFaxSendingApi(unittest.TestCase):
    """FaxSendingApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.fax_sending_api.FaxSendingApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_fax_document_id_costs_get(self):
        """Test case for fax_document_id_costs_get

        This API is for computing the cost of the fax to be sent  # noqa: E501
        """
        pass

    def test_fax_history_get(self):
        """Test case for fax_history_get

        This API gets the history of a fax  # noqa: E501
        """
        pass

    def test_fax_job_id_status_get(self):
        """Test case for fax_job_id_status_get

        This API gets the status of a fax  # noqa: E501
        """
        pass

    def test_fax_post(self):
        """Test case for fax_post

        This API is for sending a new fax in any fax numbers anywhere in the world  # noqa: E501
        """
        pass

    def test_file_clean_get(self):
        """Test case for file_clean_get

        This API is used for cleaning a document  # noqa: E501
        """
        pass

    def test_file_generate_preview_get(self):
        """Test case for file_generate_preview_get

        This API generates a preview of a document  # noqa: E501
        """
        pass

    def test_files_document_id_delete(self):
        """Test case for files_document_id_delete

        This API deletes a document  # noqa: E501
        """
        pass

    def test_files_get(self):
        """Test case for files_get

        This API gets all the files of a certain user  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
