# coding: utf-8

"""
    Fax.to REST API client for Python

    This is Fax.to REST API client for Python.  # noqa: E501

    OpenAPI spec version: 2.0.0
    Contact: inquiries@fax.to
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.inline_response20017_numbers import InlineResponse20017Numbers  # noqa: E501
from swagger_client.rest import ApiException


class TestInlineResponse20017Numbers(unittest.TestCase):
    """InlineResponse20017Numbers unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse20017Numbers(self):
        """Test InlineResponse20017Numbers"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.inline_response20017_numbers.InlineResponse20017Numbers()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
