# coding: utf-8

"""
    Fax.to REST API client for Python

    This is Fax.to REST API client for Python.  # noqa: E501

    OpenAPI spec version: 2.0.0
    Contact: inquiries@fax.to
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.user_management_api import UserManagementApi  # noqa: E501
from swagger_client.rest import ApiException


class TestUserManagementApi(unittest.TestCase):
    """UserManagementApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.user_management_api.UserManagementApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_sub_user_post(self):
        """Test case for sub_user_post

        This API creates a subuser  # noqa: E501
        """
        pass

    def test_user_login_post(self):
        """Test case for user_login_post

        This API is used for logging in on an existing user account  # noqa: E501
        """
        pass

    def test_user_post(self):
        """Test case for user_post

        This API registers a new user account  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
