# coding: utf-8

"""
    Fax.to REST API client for Python

    This is Fax.to REST API client for Python.  # noqa: E501

    OpenAPI spec version: 2.0.0
    Contact: inquiries@fax.to
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.inline_response20015_data import InlineResponse20015Data  # noqa: E501
from swagger_client.rest import ApiException


class TestInlineResponse20015Data(unittest.TestCase):
    """InlineResponse20015Data unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse20015Data(self):
        """Test InlineResponse20015Data"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.inline_response20015_data.InlineResponse20015Data()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
