# coding: utf-8

"""
    Fax.to REST API client for Python

    This is Fax.to REST API client for Python.  # noqa: E501

    OpenAPI spec version: 2.0.0
    Contact: inquiries@fax.to
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.inline_response2004_meta_pagination_links import InlineResponse2004MetaPaginationLinks  # noqa: E501
from swagger_client.rest import ApiException


class TestInlineResponse2004MetaPaginationLinks(unittest.TestCase):
    """InlineResponse2004MetaPaginationLinks unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse2004MetaPaginationLinks(self):
        """Test InlineResponse2004MetaPaginationLinks"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.inline_response2004_meta_pagination_links.InlineResponse2004MetaPaginationLinks()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
