# coding: utf-8

"""
    Fax.to REST API client for Python

    This is Fax.to REST API client for Python.  # noqa: E501

    OpenAPI spec version: 2.0.0
    Contact: inquiries@fax.to
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.fax_receiving_api import FaxReceivingApi  # noqa: E501
from swagger_client.rest import ApiException


class TestFaxReceivingApi(unittest.TestCase):
    """FaxReceivingApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.fax_receiving_api.FaxReceivingApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_area_codes_country_code_state_id_get(self):
        """Test case for area_codes_country_code_state_id_get

        This API gets a list of countries with its area code  # noqa: E501
        """
        pass

    def test_countries_country_code_did_groups_get(self):
        """Test case for countries_country_code_did_groups_get

        This API gets a list of DID groups  # noqa: E501
        """
        pass

    def test_countries_get(self):
        """Test case for countries_get

        This API gets a list of countries available in the Fax.to coverage  # noqa: E501
        """
        pass

    def test_incoming_faxes_get(self):
        """Test case for incoming_faxes_get

        This API gets a list of incoming faxes  # noqa: E501
        """
        pass

    def test_incoming_faxes_recipient_get(self):
        """Test case for incoming_faxes_recipient_get

        This API gets a list of incoming faxes for a specific recipient  # noqa: E501
        """
        pass

    def test_numbers_get(self):
        """Test case for numbers_get

        This API gets a list of numbers to get the current configuration of one or multiple number  # noqa: E501
        """
        pass

    def test_provision_numbers_get(self):
        """Test case for provision_numbers_get

        This API gets a list of provisioned numbers  # noqa: E501
        """
        pass

    def test_states_country_code_get(self):
        """Test case for states_country_code_get

        This API gets a list of states of a given country available in the Fax.to coverage  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
