# coding: utf-8

"""
    Fax.to REST API client for Python

    This is Fax.to REST API client for Python.  # noqa: E501

    OpenAPI spec version: 2.0.0
    Contact: inquiries@fax.to
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class InlineResponse20014Areacodes(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'country_code': 'str',
        'state_id': 'int',
        'area_code': 'str'
    }

    attribute_map = {
        'country_code': 'country_code',
        'state_id': 'state_id',
        'area_code': 'area_code'
    }

    def __init__(self, country_code=None, state_id=None, area_code=None):  # noqa: E501
        """InlineResponse20014Areacodes - a model defined in Swagger"""  # noqa: E501

        self._country_code = None
        self._state_id = None
        self._area_code = None
        self.discriminator = None

        if country_code is not None:
            self.country_code = country_code
        if state_id is not None:
            self.state_id = state_id
        if area_code is not None:
            self.area_code = area_code

    @property
    def country_code(self):
        """Gets the country_code of this InlineResponse20014Areacodes.  # noqa: E501


        :return: The country_code of this InlineResponse20014Areacodes.  # noqa: E501
        :rtype: str
        """
        return self._country_code

    @country_code.setter
    def country_code(self, country_code):
        """Sets the country_code of this InlineResponse20014Areacodes.


        :param country_code: The country_code of this InlineResponse20014Areacodes.  # noqa: E501
        :type: str
        """

        self._country_code = country_code

    @property
    def state_id(self):
        """Gets the state_id of this InlineResponse20014Areacodes.  # noqa: E501


        :return: The state_id of this InlineResponse20014Areacodes.  # noqa: E501
        :rtype: int
        """
        return self._state_id

    @state_id.setter
    def state_id(self, state_id):
        """Sets the state_id of this InlineResponse20014Areacodes.


        :param state_id: The state_id of this InlineResponse20014Areacodes.  # noqa: E501
        :type: int
        """

        self._state_id = state_id

    @property
    def area_code(self):
        """Gets the area_code of this InlineResponse20014Areacodes.  # noqa: E501


        :return: The area_code of this InlineResponse20014Areacodes.  # noqa: E501
        :rtype: str
        """
        return self._area_code

    @area_code.setter
    def area_code(self, area_code):
        """Sets the area_code of this InlineResponse20014Areacodes.


        :param area_code: The area_code of this InlineResponse20014Areacodes.  # noqa: E501
        :type: str
        """

        self._area_code = area_code

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InlineResponse20014Areacodes):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
