# coding: utf-8

"""
    Fax.to REST API client for Python

    This is Fax.to REST API client for Python.  # noqa: E501

    OpenAPI spec version: 2.0.0
    Contact: inquiries@fax.to
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class InlineResponse20016Data(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'int',
        'did_id': 'int',
        'did_group_id': 'int',
        'country_code': 'str',
        'city_name': 'str',
        'area_code': 'str',
        'number': 'str',
        'type': 'str',
        'trunk_id': 'int'
    }

    attribute_map = {
        'id': 'id',
        'did_id': 'did_id',
        'did_group_id': 'did_group_id',
        'country_code': 'country_code',
        'city_name': 'city_name',
        'area_code': 'area_code',
        'number': 'number',
        'type': 'type',
        'trunk_id': 'trunk_id'
    }

    def __init__(self, id=None, did_id=None, did_group_id=None, country_code=None, city_name=None, area_code=None, number=None, type=None, trunk_id=None):  # noqa: E501
        """InlineResponse20016Data - a model defined in Swagger"""  # noqa: E501

        self._id = None
        self._did_id = None
        self._did_group_id = None
        self._country_code = None
        self._city_name = None
        self._area_code = None
        self._number = None
        self._type = None
        self._trunk_id = None
        self.discriminator = None

        if id is not None:
            self.id = id
        if did_id is not None:
            self.did_id = did_id
        if did_group_id is not None:
            self.did_group_id = did_group_id
        if country_code is not None:
            self.country_code = country_code
        if city_name is not None:
            self.city_name = city_name
        if area_code is not None:
            self.area_code = area_code
        if number is not None:
            self.number = number
        if type is not None:
            self.type = type
        if trunk_id is not None:
            self.trunk_id = trunk_id

    @property
    def id(self):
        """Gets the id of this InlineResponse20016Data.  # noqa: E501


        :return: The id of this InlineResponse20016Data.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this InlineResponse20016Data.


        :param id: The id of this InlineResponse20016Data.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def did_id(self):
        """Gets the did_id of this InlineResponse20016Data.  # noqa: E501


        :return: The did_id of this InlineResponse20016Data.  # noqa: E501
        :rtype: int
        """
        return self._did_id

    @did_id.setter
    def did_id(self, did_id):
        """Sets the did_id of this InlineResponse20016Data.


        :param did_id: The did_id of this InlineResponse20016Data.  # noqa: E501
        :type: int
        """

        self._did_id = did_id

    @property
    def did_group_id(self):
        """Gets the did_group_id of this InlineResponse20016Data.  # noqa: E501


        :return: The did_group_id of this InlineResponse20016Data.  # noqa: E501
        :rtype: int
        """
        return self._did_group_id

    @did_group_id.setter
    def did_group_id(self, did_group_id):
        """Sets the did_group_id of this InlineResponse20016Data.


        :param did_group_id: The did_group_id of this InlineResponse20016Data.  # noqa: E501
        :type: int
        """

        self._did_group_id = did_group_id

    @property
    def country_code(self):
        """Gets the country_code of this InlineResponse20016Data.  # noqa: E501


        :return: The country_code of this InlineResponse20016Data.  # noqa: E501
        :rtype: str
        """
        return self._country_code

    @country_code.setter
    def country_code(self, country_code):
        """Sets the country_code of this InlineResponse20016Data.


        :param country_code: The country_code of this InlineResponse20016Data.  # noqa: E501
        :type: str
        """

        self._country_code = country_code

    @property
    def city_name(self):
        """Gets the city_name of this InlineResponse20016Data.  # noqa: E501


        :return: The city_name of this InlineResponse20016Data.  # noqa: E501
        :rtype: str
        """
        return self._city_name

    @city_name.setter
    def city_name(self, city_name):
        """Sets the city_name of this InlineResponse20016Data.


        :param city_name: The city_name of this InlineResponse20016Data.  # noqa: E501
        :type: str
        """

        self._city_name = city_name

    @property
    def area_code(self):
        """Gets the area_code of this InlineResponse20016Data.  # noqa: E501


        :return: The area_code of this InlineResponse20016Data.  # noqa: E501
        :rtype: str
        """
        return self._area_code

    @area_code.setter
    def area_code(self, area_code):
        """Sets the area_code of this InlineResponse20016Data.


        :param area_code: The area_code of this InlineResponse20016Data.  # noqa: E501
        :type: str
        """

        self._area_code = area_code

    @property
    def number(self):
        """Gets the number of this InlineResponse20016Data.  # noqa: E501


        :return: The number of this InlineResponse20016Data.  # noqa: E501
        :rtype: str
        """
        return self._number

    @number.setter
    def number(self, number):
        """Sets the number of this InlineResponse20016Data.


        :param number: The number of this InlineResponse20016Data.  # noqa: E501
        :type: str
        """

        self._number = number

    @property
    def type(self):
        """Gets the type of this InlineResponse20016Data.  # noqa: E501


        :return: The type of this InlineResponse20016Data.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this InlineResponse20016Data.


        :param type: The type of this InlineResponse20016Data.  # noqa: E501
        :type: str
        """

        self._type = type

    @property
    def trunk_id(self):
        """Gets the trunk_id of this InlineResponse20016Data.  # noqa: E501


        :return: The trunk_id of this InlineResponse20016Data.  # noqa: E501
        :rtype: int
        """
        return self._trunk_id

    @trunk_id.setter
    def trunk_id(self, trunk_id):
        """Sets the trunk_id of this InlineResponse20016Data.


        :param trunk_id: The trunk_id of this InlineResponse20016Data.  # noqa: E501
        :type: int
        """

        self._trunk_id = trunk_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InlineResponse20016Data):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
