# coding: utf-8

"""
    Fax.to REST API client for Python

    This is Fax.to REST API client for Python.  # noqa: E501

    OpenAPI spec version: 2.0.0
    Contact: inquiries@fax.to
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class InlineResponse200(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'status': 'str',
        'fax_job_id': 'int',
        'user_cash_balance': 'float',
        'cost': 'float'
    }

    attribute_map = {
        'status': 'status',
        'fax_job_id': 'fax_job_id',
        'user_cash_balance': 'user_cash_balance',
        'cost': 'cost'
    }

    def __init__(self, status=None, fax_job_id=None, user_cash_balance=None, cost=None):  # noqa: E501
        """InlineResponse200 - a model defined in Swagger"""  # noqa: E501

        self._status = None
        self._fax_job_id = None
        self._user_cash_balance = None
        self._cost = None
        self.discriminator = None

        if status is not None:
            self.status = status
        if fax_job_id is not None:
            self.fax_job_id = fax_job_id
        if user_cash_balance is not None:
            self.user_cash_balance = user_cash_balance
        if cost is not None:
            self.cost = cost

    @property
    def status(self):
        """Gets the status of this InlineResponse200.  # noqa: E501

        The status of the API request  # noqa: E501

        :return: The status of this InlineResponse200.  # noqa: E501
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this InlineResponse200.

        The status of the API request  # noqa: E501

        :param status: The status of this InlineResponse200.  # noqa: E501
        :type: str
        """

        self._status = status

    @property
    def fax_job_id(self):
        """Gets the fax_job_id of this InlineResponse200.  # noqa: E501

        The id of the fax job. It is used to check the status of the fax job.  # noqa: E501

        :return: The fax_job_id of this InlineResponse200.  # noqa: E501
        :rtype: int
        """
        return self._fax_job_id

    @fax_job_id.setter
    def fax_job_id(self, fax_job_id):
        """Sets the fax_job_id of this InlineResponse200.

        The id of the fax job. It is used to check the status of the fax job.  # noqa: E501

        :param fax_job_id: The fax_job_id of this InlineResponse200.  # noqa: E501
        :type: int
        """

        self._fax_job_id = fax_job_id

    @property
    def user_cash_balance(self):
        """Gets the user_cash_balance of this InlineResponse200.  # noqa: E501

        The remaining cash balance  # noqa: E501

        :return: The user_cash_balance of this InlineResponse200.  # noqa: E501
        :rtype: float
        """
        return self._user_cash_balance

    @user_cash_balance.setter
    def user_cash_balance(self, user_cash_balance):
        """Sets the user_cash_balance of this InlineResponse200.

        The remaining cash balance  # noqa: E501

        :param user_cash_balance: The user_cash_balance of this InlineResponse200.  # noqa: E501
        :type: float
        """

        self._user_cash_balance = user_cash_balance

    @property
    def cost(self):
        """Gets the cost of this InlineResponse200.  # noqa: E501

        The cost of sending fax  # noqa: E501

        :return: The cost of this InlineResponse200.  # noqa: E501
        :rtype: float
        """
        return self._cost

    @cost.setter
    def cost(self, cost):
        """Sets the cost of this InlineResponse200.

        The cost of sending fax  # noqa: E501

        :param cost: The cost of this InlineResponse200.  # noqa: E501
        :type: float
        """

        self._cost = cost

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InlineResponse200):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
